### ISSUE TITLE
Counter Error

### ISSUE THREAD

**Issue by yqcmail** [SpinalHDL/SpinalWorkshop#14]
I run:
sbt "runMain workshop.counter.CounterMain"

info:

[info] welcome to sbt 1.4.7 (Debian Java 11.0.14)
[info] loading settings for project spinalworkshop-build from plugins.sbt ...
[info] loading project definition from /home/admin/spinal_prj/SpinalWorkshop/project
[info] loading settings for project spinalworkshop from build.sbt ...
[info] set current project to SpinalWorkshop (in build file:/home/admin/spinal_prj/SpinalWorkshop/)
[info] running (fork) workshop.counter.CounterMain 
[info] [Runtime] SpinalHDL v1.6.4    git head : 598c18959149eb18e5eee5b0aa3eef01ecaa41a1
[info] [Runtime] JVM max memory : 988.0MiB
[info] [Runtime] Current date : 2022.04.22 02:05:16
[info] [Progress] at 0.000 : Elaborate components
[info] [Progress] at 0.311 : Checks and transforms
[info] **********************************************************************************************
[info] [Warning] Elaboration failed (3 errors).
[info]           Spinal will restart with scala trace to help you to find the problem.
[info] **********************************************************************************************
[info] [Progress] at 0.371 : Elaborate components
[info] [Progress] at 0.382 : Checks and transforms
[error] Exception in thread "main" spinal.core.SpinalExit: 
[error]  Error detected in phase PhaseCheck_noLatchNoOverride
[error] ********************************************************************************
[error] ********************************************************************************
[error] NO DRIVER ON (toplevel/io_value : out UInt[4 bits]), defined at
[error]     workshop.counter.Counter$$anon$1.<init>(Counter.scala:8)
[error]     workshop.counter.Counter.<init>(Counter.scala:6)
[error]     workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8)
[error]     workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8)
[error]     spinal.sim.JvmThread.run(SimManager.scala:51)
[error] ********************************************************************************
[error] ********************************************************************************
[error] NO DRIVER ON (toplevel/io_full : out Bool), defined at
[error]     workshop.counter.Counter$$anon$1.<init>(Counter.scala:9)
[error]     workshop.counter.Counter.<init>(Counter.scala:6)
[error]     workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8)
[error]     workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8)
[error]     spinal.sim.JvmThread.run(SimManager.scala:51)
[error] ********************************************************************************
[error] ********************************************************************************
[error] Design's errors are listed above.
[error] SpinalHDL compiler exit stack : 
[error] 	at spinal.core.SpinalExit$.apply(Misc.scala:425)
[error] 	at spinal.core.SpinalError$.apply(Misc.scala:480)
[error] 	at spinal.core.internals.PhaseContext.checkPendingErrors(Phase.scala:175)
[error] 	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:191)
[error] 	at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1$$anonfun$apply$115.apply(Phase.scala:2455)
[error] 	at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1$$anonfun$apply$115.apply(Phase.scala:2453)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1.apply(Phase.scala:2453)
[error] 	at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1.apply(Phase.scala:2389)
[error] 	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:69)
[error] 	at spinal.core.internals.SpinalVhdlBoot$.singleShot(Phase.scala:2389)
[error] 	at spinal.core.internals.SpinalVhdlBoot$.apply(Phase.scala:2384)
[error] 	at spinal.core.Spinal$.apply(Spinal.scala:379)
[error] 	at spinal.core.SpinalConfig.generateVhdl(Spinal.scala:163)
[error] 	at workshop.counter.CounterMain$.main(CounterMain.scala:8)
[error] 	at workshop.counter.CounterMain.main(CounterMain.scala)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 3 s, completed Apr 22, 2022, 2:05:17 AM

**Comment by yqcmail** [comment]
I force out port:
io.value := U(0)
  io.full := True 

So it's  ok.
