### ISSUE TITLE
 Error detected in phase PhaseCheck_noLatchNoOverride

### ISSUE THREAD

**Issue by 0806gcx** [SpinalHDL/SpinalWorkshop#15]

**Comment by 0806gcx** [comment]
> Hi,
> 
> I'm trying the code counter, there are some errors .I don't know how to overcome it! `Error detected in phase PhaseCheck_noLatchNoOverride
> 
> NO DRIVER ON (toplevel/io_value : out UInt[4 bits]), defined at workshop.counter.Counter$$anon$1.(Counter.scala:8) workshop.counter.Counter.(Counter.scala:6) workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8) workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8) spinal.sim.JvmThread.run(SimManager.scala:51)
> 
> NO DRIVER ON (toplevel/io_full : out Bool), defined at workshop.counter.Counter$$anon$1.(Counter.scala:9) workshop.counter.Counter.(Counter.scala:6) workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8) workshop.counter.CounterMain$$anonfun$main$1.apply(CounterMain.scala:8) spinal.sim.JvmThread.run(SimManager.scala:51)
> 
> Design's errors are listed above. SpinalHDL compiler exit stack :
> 
> ```
> at spinal.core.SpinalExit$.apply(Misc.scala:425)
> at spinal.core.SpinalError$.apply(Misc.scala:480)
> at spinal.core.internals.PhaseContext.checkPendingErrors(Phase.scala:175)
> at spinal.core.internals.PhaseContext.doPhase(Phase.scala:191)
> at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1$$anonfun$apply$115.apply(Phase.scala:2455)
> at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1$$anonfun$apply$115.apply(Phase.scala:2453)
> at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1.apply(Phase.scala:2453)
> at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$1.apply(Phase.scala:2389)
> at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:69)
> at spinal.core.internals.SpinalVhdlBoot$.singleShot(Phase.scala:2389)
> at spinal.core.internals.SpinalVhdlBoot$.apply(Phase.scala:2384)
> at spinal.core.Spinal$.apply(Spinal.scala:379)
> at spinal.core.SpinalConfig.generateVhdl(Spinal.scala:163)
> at workshop.counter.CounterMain$.main(CounterMain.scala:8)
> at workshop.counter.CounterMain.main(CounterMain.scala)`
> ```
